# Generated by Django 3.2.9 on 2021-11-04 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_alter_funcionario_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='departamento',
            new_name='departamentos',
        ),
    ]
